### ISSUE TITLE
Filtro por tag

### ISSUE THREAD

**Issue by Kenzitron** [Kenzitron/cas2017-website#10]
Estaría bien poder filtrar por tag. que aparecieran todos los tags y se marcaran unos si otros no o de alguna manera.

**Comment by nachodev** [comment]
En el nuevo diseño está metido. Yo me he peleado mucho con Isotope, no me importa quedarme esta issue

**Comment by nachodev** [comment]
Esta tarea depende de la[ issue 19: Maquetacion de los nuevos filtros](https://github.com/Kenzitron/cas2017-website/issues/19). El filtrado se hace con isotope. Si no lo habéis usado, dejádmelo que tardo 0' una vez que esté la maquetación. No filtréis con otra herramienta pls, para tener coherencia.
