### ISSUE TITLE
Solo puedo puntuar hasta 10

### ISSUE THREAD

**Issue by Kenzitron** [Kenzitron/cas2017-website#11]
Aunque tenga 12 votos, solo me aparecen 10 Botones para puntuar.

**Comment by nachodev** [comment]
Yo entiendo que las charlas se puntúan del 1 al 10. Si tienes 12 votos, podrás distribuir más votos. Cambiarlo es fácil, no se como lo ves.

**Comment by Kenzitron** [comment]
​Yo creo que se debería poder darlos todos a la misma charla, sean 10, 11 o
80. Si, es fácil daría la libertad.​

**Comment by nachodev** [comment]
Yo creo que después de la conversación que tuvimos el otro día, estaría bien "obligar" a la gente a distribuir las votaciones. Así , aunque haya amiguismos, podemos ver que interesa a la gente realmente.
